---
title: "Figures, June 2026"
author: "Kropko"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, warning=FALSE, message=FALSE}
library(tidyverse)
library(DT)
library(summarytools)
library(wordcloud)
library(wordcloud2)
library(RColorBrewer)
```

The cleaned survey data exist in the following CSV file:

```{r, message=FALSE, warning=FALSE}
pbs <- read_csv("data_clean.csv")
```

## Which variables?

You can also embed plots, for example:

```{r, echo=FALSE}
table(pbs$politics, pbs$subscription_pbs) #FIG 3

pbs_bar <- pbs %>%
  mutate(politics = fct_relevel(politics, "Extremely liberal",
                                "Moderately liberal",
                                "Slightly liberal",
                                "Neither liberal nor conservative",
                                "Slightly conservative",
                                "Moderately conservative",
                                "Extremely conservative"),
         politics = fct_recode(politics,"Extremely \n liberal"="Extremely liberal",
                                "Moderately \n liberal" = "Moderately liberal",
                                "Slightly \n liberal" = "Slightly liberal",
                                "Neither liberal \n nor conservative" = "Neither liberal nor conservative",
                                "Slightly \n conservative" = "Slightly conservative",
                                "Moderately \n conservative" = "Moderately conservative",
                                "Extremely \n conservative" = "Extremely conservative")) %>%
  group_by(politics, subscription_pbs) %>%
  summarize(count=n()) %>%
  ungroup() %>%
  group_by(politics) %>%
  mutate(count2 = sum(count)) %>%
  ungroup() %>%
  mutate(percent = paste(as.character(round(100*count/count2, 2)),"%",sep=""))
pbs_bar

g <- ggplot(pbs_bar, aes(x = politics, y = count, fill = subscription_pbs)) +
  geom_col(position = "dodge") +
  xlab("When it comes to politics, how would you describe yourself?") +
  ylab("Frequency") +
  guides(fill=guide_legend(title="Is PBS a source of news \n and election coverage?")) +
  geom_text(aes(label=percent), color = "white", vjust=1.6) +
  theme(text=element_text(family="serif")) 
g

ggsave("figure3.pdf", width=12, height=6)

```


```{r, echo=FALSE}
table(pbs$levelofbias_pbsnews) # FIG 1
```
```{r, echo=FALSE}
pbs_bar <- subset(pbs, !is.na(pbs$levelofbias_pbsnews))
pbs_bar <- pbs_bar %>%
  mutate(levelofbias_pbsnews = fct_relevel(levelofbias_pbsnews, c("Totally left", "Left leaning", "Neutral / All sides", "Right leaning", "Totally right"))) %>%
  group_by(levelofbias_pbsnews) %>%
  summarize(count=n()) %>%
  ungroup() %>%
  mutate(percent = paste(as.character(round(100*count/sum(count),2)), "%", sep=""))

g <- ggplot(pbs_bar, aes(x=levelofbias_pbsnews, y=count)) +
  geom_col(fill="blue") +
  xlab("Perception of bias in PBS News") +
  ylab("Frequency") +
  geom_text(aes(label=percent), color = "white", vjust=1.6) +
  theme(text=element_text(family="serif")) 
g

ggsave("figure1.pdf", width=6, height=6)
```

```{r, echo=FALSE} 
table(pbs$levelofbias_pbsorganisation) #FIG 2

pbs_bar <- subset(pbs, !is.na(pbs$levelofbias_pbsorganisation))
pbs_bar <- pbs_bar %>%
  mutate(levelofbias_pbsorganisation = fct_relevel(levelofbias_pbsorganisation, c("Totally left", "Left leaning", "Neutral / All sides", "Right leaning", "Totally right"))) %>%
  group_by(levelofbias_pbsorganisation) %>%
  summarize(count=n()) %>%
  ungroup() %>%
  mutate(percent = paste(as.character(round(100*count/sum(count),2)), "%", sep=""))

g <- ggplot(pbs_bar, aes(x=levelofbias_pbsorganisation, y=count)) +
  geom_col(fill="blue") +
  xlab("Perception of bias in PBS as an organization") +
  ylab("Frequency") +
  geom_text(aes(label=percent), color = "white", vjust=1.6) +
  theme(text=element_text(family="serif")) 
g

ggsave("figure2.pdf", width=6, height=6)
```